------------------------------------------
Запросы аутентификации
------------------------------------------
GET запрос для signup_view:

URL: /signup/

GET параметры: отсутствуют

POST запрос для signup_view:

URL: /signup/

POST параметры:
- username (строка)
- email (строка)
- password (строка)

GET запрос для login_view:

URL: /login/

GET параметры: отсутствуют

POST запрос для login_view:

URL: /login/

POST параметры:
- username (строка)
- password (строка)

------------------------------------------
Запросы отправки сообщений
------------------------------------------